name: build and test

on: [push]

jobs:
  build-Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: apt-get
      run: sudo apt-get install -y libxrandr-dev

    - name: build and run
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release -j
        # cmake --build . --config Release --target test

  build-MacOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: build and run
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release -j
        # ctest -V
        # cmake --build . --config Release --target test

  build-Windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: build and run
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_GENERATOR_PLATFORM=x64
        cmake --build . --config Release -j
        # cmake --build . --config Release --target run_unit_tests
